Update django.yml

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -23,5 +23,11 @@ jobs:
 
       - name: Install dependencies
         run: |
-          pip install -r requirements.txt
-        working-directory: ./ScheduleBuilder
+          cd ./ScheduleBuilder  # Change to the directory containing requirements.txt
+          if [ -f "requirements.txt" ]; then
+            pip install -r requirements.txt
+          else
+            echo "requirements.txt not found in the specified directory."
+            exit 1
+          fi
+        working-directory: ${{ github.workspace }}
